### ISSUE TITLE
Empty Tracks property of a Media

### ISSUE THREAD

**Issue by fededim** [Zastai/MusicBrainz#5] opened 2020-01-21 11:40 UTC
Hi,

I am issuing the following query
` 

            Query a = new Query("AutoTagger");
            
            var ris=a.FindRecordings("the right thing simply red AND dur:[224000 TO 254000]");

            foreach (var r in ris.Results)
            {
                if (r.Releases.Count > 0)
                    if (r.Releases[0].Media.Count > 0)
                    {
                        var m = r.Releases[0].Media[0];
                    }
            }
`

The problem is that the Tracks property of m variable is null whereas if I call directly the [webservice](https://musicbrainz.org/ws/2/recording?query=the%20right%20thing%20simply%20red%20AND%20dur:[224000%20TO%20254000]) the XML shows that it is populated by 1 track, which unluckily is not deserialized. Can anybody tell me why ?

**Comment by Zastai** [comment] 2020-01-21 11:49
Hmm. I’m traveling so can’t check this right now. If you create a debug build of the libraries, they will send the requests made and json received to the debug output. That would at least show whether the library is getting the same response your manual query does.

**Comment by Zastai** [comment] 2020-01-21 11:56
You could also try [https://ci.appveyor.com/project/Zastai/musicbrainz/build/artifacts](the last AppVeyor build) to see if that helps matters. I don’t think I touched anything in that part yet, but you never know.

Note that I am reworking all the libraries to use System.Text.Json instead of JSON.NET, so if this is a bug, I might not release a separate fix for this, but instead just test this case as part of that switchover.

**Comment by Zastai** [comment] 2020-01-22 20:56
Reproduced and looking into it. The position, count and offset come in fine, tracks don't, despite being in the JSON.

**Comment by Zastai** [comment] 2020-01-22 21:11
Ah I see what the problem is - it looks like for a query like this, the medium data includes a "track" property instead of a "tracks" property, and the library only handles "tracks". I'll adjust things to handle both and to have Tracks be whichever is present (if both are found, "tracks" will win).

**Closed as completed** 2020-01-22 21:22 UTC

**Comment by Zastai** [comment] 2020-01-22 21:41
Pending the next release, you can try the NuGet packages from https://ci.appveyor.com/project/Zastai/musicbrainz/builds/30295401/artifacts

**Comment by fededim** [comment] 2020-01-23 08:56
Ok, thank you for the quick patch!
